#配置myBatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/model/*Mapper.xml
  global-config:
    db-config:
      #逻辑删除
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #Show Sql on Terminal log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.124.79:3306/Vulcan?serverTimezone=GMT%2B8
    username: vulcan
    password: 990312lllLLL???
  output:
    ansi:
      enabled: always
server:
  port: 9990


logging:
  config: classpath:logback-spring.xml